server:
  port: 8080
logging:
  level:
    com.xg: debug
    web: debug

#datasource: connect to mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mind?characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  #目的是为了省略resultType里的代码量: 注册实体类
  type-aliases-package: com.xg.entity
  #设置配置的日志输出信息: 为了看到sql语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
