server:
  port: 8080
logging:
  level:
    com.xg: debug
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mind?characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: 123456
    hikari:
      #设置事务自动提交(单sql语句事务情况)
      auto-commit: true
      #设置最大连接数
      maximum-pool-size: 10
      minimum-idle: 10
      #获取连接是，检测语句
      connection-test-query: select 1
      #连接超时设置
      connection-timeout: 20000
      #其它属性

#mybatis-plus config
mybatis-plus:
  configuration:
    #开启驼峰命名自动映射
    map-underscore-to-camel-case: true
    #开启日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.xg.entity
  #扫描mapper文件
  mapper-locations: classpath:mapper/**/*.xml